batch_size: 1
body_min_w: 64
path_track: 20
body_res:
- 256
- 128
display_video_flag: false
img_size: 416
max_cosine_distance: 0.2
encoder_filename: models/mars-small128.pb
detector_name: yolov4
detector_filename: models/yolov4.h5
save_video_flag: true
skip_frames: 4
yolo_max_boxes: 64
yolo_iou_threshold: 0.5
yolo_score_threshold: 0.5
