autostart_gpus_list:
- device0
autostart_streams:
- cherk_right
cpu_config: device0
gpus_configs_list:
- device0
- device1
streams:
- file_39
- cherk_left
- cherk_right
- fabrika_1
- fabrika_2
- testvlc
- testvlc2
- testvlc3
- testvlc8
- testvlc9
- testvlc10
- testvlc11
- testvlc12
- cherk_left_09_13
- cherk_left_13_17
- cherk_left_17_21
- cherk_right_09_15
- cherk_right_15_21
- 5min_lev
- 5min_prav
