id: test00
url: video/39.avi
isFromFile: true
save_path: video/39_out.avi
body_min_w: 64
path_track: 20
body_res:
- 256
- 128
display_video_flag: true
max_cosine_distance: 0.2
save_video_flag: true
skip_frames: 0
encoder_filename: mars-small128.pb
batch_size: 32
img_size_start:
- 1600
- 1200
save_video_res:
- 720
- 540
borders:
  border1:
  - - 0
    - 104
  - - 312
    - 104
