batch_size: 32
body_min_w: 64
body_res:
- 256
- 128
borders:
  border1:
  - - 0
    - 104
  - - 312
    - 104
display_video_flag: true
encoder_filename: mars-small128.pb
img_size_start:
- 1600
- 1200
isFromFile: true
max_cosine_distance: 0.2
name: test00
path_track: 20
save_path: videos/39_out.avi
save_video_flag: true
save_video_res:
- 720
- 540
skip_frames: 1
type: 0
url: video/39.avi
